from apps.home_app import HomeApp
from apps.login_app import LoginApp
from apps.myloading_app import MyLoadingApp
from apps.signup import SignUpApp
from apps.project_setup import ProjectSetupApp
from apps.data import DataApp
from apps.model_setup import ModelSetupApp
from apps.training import TrainingApp
from apps.prediction import PredictionApp
from apps.dashboard import DashboardApp
